# Assignment 25 - Feb 26' 23 - NumPy

## Consider the below code to answer further questions.

In [1]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

###  1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

Yes. The data type of variable list_ is *list* whereas the data type of variable array_list is *numpy array*

In [2]:
type(list_)

list

In [3]:
type(array_list)

numpy.ndarray

### 2.  Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [10]:
# code to print the data type of each and every element of list_

print("Data type of all the elements in list_")
for i in list_:
    print(f"type of {i} is: {type(i)}")

Data type of all the elements in list_
type of 1 is: <class 'str'>
type of 2 is: <class 'str'>
type of 3 is: <class 'str'>
type of 4 is: <class 'str'>
type of 5 is: <class 'str'>


In [12]:
# code to print the data type of each and every element of array_list

print("Data type of all the elements in array_list")
for i in array_list:
    print(f"type of {i} is: {type(i)}")

Data type of all the elements in array_list
type of 1 is: <class 'numpy.str_'>
type of 2 is: <class 'numpy.str_'>
type of 3 is: <class 'numpy.str_'>
type of 4 is: <class 'numpy.str_'>
type of 5 is: <class 'numpy.str_'>


### 3. Considering the following changes in the variable, array_list:
* array_list = np.array(object = list_, dtype = int)
### Will there be any difference in the data type of the elements present in both the variables, list_ and array_list? If so then print the data types of each and every element present in both the variables, list_ and array_list.

In [13]:
array_list = np.array(object = list_, dtype = int)

Yes. The data type of the elements present in both the variables, list_ and array_list will be different.

In [16]:
# code to print the data type of each and every element of list_

print("Data type of all the elements in list_")
for i in list_:
    print(f"type of {i} is: {type(i)}")
    
print("\n")

# code to print the data type of each and every element of array_list

print("Data type of all the elements in array_list")
for i in array_list:
    print(f"type of {i} is: {type(i)}")

Data type of all the elements in list_
type of 1 is: <class 'str'>
type of 2 is: <class 'str'>
type of 3 is: <class 'str'>
type of 4 is: <class 'str'>
type of 5 is: <class 'str'>


Data type of all the elements in array_list
type of 1 is: <class 'numpy.int64'>
type of 2 is: <class 'numpy.int64'>
type of 3 is: <class 'numpy.int64'>
type of 4 is: <class 'numpy.int64'>
type of 5 is: <class 'numpy.int64'>


## Consider the below code to answer further questions.

In [18]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
num_array

array([[1, 2, 3],
       [4, 5, 6]])

### 4.  Write a code to find the following characteristics of variable, num_array:
#### (i)	 shape
#### (ii) size

In [20]:
# i. shape 
print(f"The shape of num_array is: {num_array.shape}")

The shape of num_array is: (2, 3)


In [22]:
# ii. size
print(f"The size of num_array is: {num_array.size}")

The size of num_array is: 6


### 5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [26]:
# code to create numpy array of 3*3 matrix containing zeros only
zero_matrix = np.zeros((3,3))
zero_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
print(f"The shape of zero matrix is: {zero_matrix.shape}")
print(f"The size of zero matrix is: {zero_matrix.size}")

The shape of zero matrix is: (3, 3)
The size of zero matrix is: 9


### 6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [30]:
identity_matrix = np.eye(5, dtype=int)
identity_matrix

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [31]:
np.identity(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])